# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2b664f93ce669f1cab4eed88698ef4fdefe2ebc43c942eddb2df752c30aa4078f25417eebbd5da4532c25fbb0580dc08a8daf9d45d4ea2565d53fd2232cfbe9

test:
  secret_key_base: babd2136dc86424035e96e633932debb1fcd68919513b4de1a6ec2aa452c9384b4f4aa75ae2826f9bfa2a847788b25a5bd81a2d6605eb190af5b6a612f111504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
